name: Continuous Delivery
on: 
    push:
        branches:
            - main # Ou qualquer outra branch

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery 
        uses: actions/upload-artifact@v4
        with:
          name: Projeto.zip
          path: |
            "**.py"
            README.md